import { PBSpecialty, PBSpecialtyText } from "./enum";

export const speciality = [
  { id: "ALL", text: "전체보기" },
  { id: PBSpecialty.KOREAN_STOCK, text: PBSpecialtyText.KOREAN_STOCK },
  { id: PBSpecialty.US_STOCK, text: PBSpecialtyText.US_STOCK },
  { id: PBSpecialty.BOND, text: PBSpecialtyText.BOND },
  { id: PBSpecialty.WRAP, text: PBSpecialtyText.WRAP },
  { id: PBSpecialty.FUND, text: PBSpecialtyText.FUND },
  { id: PBSpecialty.DERIVATIVE, text: PBSpecialtyText.DERIVATIVE },
  { id: PBSpecialty.ETF, text: PBSpecialtyText.ETF },
  { id: PBSpecialty.REAL_ESTATE, text: PBSpecialtyText.REAL_ESTATE },
];

export const company = [
  { id: "ALL", text: "전체보기" },
  { id: "ALL1", text: "미래에셋" },
  { id: "ALL2", text: "키움" },
  { id: "ALL3", text: "카카오페이" },
  { id: "ALL4", text: "삼성" },
  { id: "ALL5", text: "한국투자" },
  { id: "ALL6", text: "NH투자" },
  { id: "ALL7", text: "KB증권" },
  { id: "ALL8", text: "하나금융투자" },
  { id: "ALL9", text: "유안타" },
  { id: "ALL10", text: "신한투자" },
  { id: "ALL11", text: "대신" },
  { id: "ALL12", text: "메리츠" },
  { id: "ALL13", text: "교보" },
  { id: "ALL14", text: "신영" },
  { id: "ALL15", text: "현대차" },
  { id: "ALL16", text: "토스" },
  { id: "ALL17", text: "BNK투자" },
  { id: "ALL18", text: "IBK투자" },
  { id: "ALL19", text: "유진투자" },
  { id: "ALL20", text: "이베스트투자" },
  { id: "ALL21", text: "DB금융투자" },
  { id: "ALL22", text: "다올투자" },
  { id: "ALL23", text: "부국" },
  { id: "ALL24", text: "SK" },
  { id: "ALL25", text: "한국포스" },
  { id: "ALL26", text: "케이프투자" },
  { id: "ALL27", text: "우리종합금융" },
  { id: "ALL28", text: "한국증권금융" },
];
