export const OPTIONS = [
  { href: "/main" },
  { href: "/analysis", title: "투자 성향 알아보기", hasBack: true },
  { href: "/bookmark/content", title: "콘텐츠 북마크 목록", hasBack: true },
  { href: "/bookmark/pb", title: "PB 북마크 목록", hasBack: true },
  { href: "/contents/edit", title: "콘텐츠 수정하기", hasBack: true },
  { href: "/contents/temporary", title: "임시저장 콘텐츠", hasBack: true },
  { href: "/contents/write", title: "콘텐츠 작성하기", hasBack: true },
  { href: "/contents", title: "콘텐츠", hasBack: true },
  { href: "/detail/content", title: "PB 상세프로필", hasBack: true },
  { href: "/detail/info", title: "PB 상세프로필", hasBack: true },
  { href: "/detail/review", title: "후기 전체보기", hasBack: true },
  { href: "/faq", title: "자주 묻는 질문", hasBack: true },
  { href: "/privacy", title: "개인정보 처리방침", hasBack: true },
  { href: "/login/user", title: "유저 로그인", hasBack: true, backGroundWhite: true },
  { href: "/login/pb", title: "PB 로그인", hasBack: true, backGroundWhite: true },
  { href: "/join/user", title: "유저 회원가입", hasBack: true, backGroundWhite: true },
  { href: "/join/pb", title: "PB 회원가입", hasBack: true, backGroundWhite: true },
  { href: "/findEmail/user", title: "유저 이메일 찾기", hasBack: true, backGroundWhite: true },
  { href: "/findPassword/user", title: "유저 비밀번호 찾기", hasBack: true, backGroundWhite: true },
  { href: "/findEmail/pb", title: "PB 이메일 찾기", hasBack: true, backGroundWhite: true },
  { href: "/findPassword/pb", title: "PB 비밀번호 찾기", hasBack: true, backGroundWhite: true },
  { href: "/lounge/new", title: "최신 콘텐츠", hasBack: true },
  { href: "/lounge/hot", title: "인기 콘텐츠", hasBack: true },
  { href: "/lounge/search", title: "검색하기", hasBack: true },
  { href: "/lounge", title: "라운지" },
  { href: "/management/newReservation", title: "신규예약", hasBack: true, path: "/management?process=APPLY" },
  {
    href: "/management/confirmedReservation",
    title: "확정된 상담",
    hasBack: true,
    path: "/management?process=CONFIRM",
  },
  {
    href: "/management/completedConsultation",
    title: "완료된 상담",
    hasBack: true,
    path: "/management?process=COMPLETE",
  },
  {
    href: "/management/canceledConsultation",
    title: "취소된 상담",
    hasBack: true,
    path: "/management?process=WITHDRAW",
  },
  { href: "/management", title: "고객관리", hasBack: true },

  {
    href: "/myCounseling/newReservation",
    title: "신규예약",
    hasBack: true,
    path: "/myCounseling?process=APPLY",
  },
  {
    href: "/myCounseling/confirmedReservation",
    title: "확정된 상담",
    hasBack: true,
    path: "/myCounseling?process=CONFIRM",
  },
  {
    href: "/myCounseling/completedConsultation",
    title: "완료된 상담",
    hasBack: true,
    path: "/myCounseling?process=COMPLETE",
  },
  {
    href: "/myCounseling/canceledConsultation",
    title: "취소된 상담",
    hasBack: true,
    path: "/myCounseling?process=WITHDRAW",
  },
  { href: "/myCounseling/myReview", title: "나의 후기", hasBack: true },
  { href: "/myCounseling/reviewWrite", title: "후기 작성", hasBack: true },
  { href: "/myCounseling", title: "고객관리", hasBack: true },
  { href: "/reservation/complete", title: "상담 예약 완료", hasBack: true },
  { href: "/reservation", title: "상담 예약", hasBack: true },
  { href: "/my/editInfo", title: "개인 정보 수정", hasBack: true },
  { href: "/my/propenslty", title: "나의 투자 성향 분석", hasBack: true },
  { href: "/my/editProfile", title: "프로필 수정", hasBack: true },
  { href: "/my/editProfile", title: "프로필 수정", hasBack: true },
  { href: "/my", title: "마이페이지", hasBack: true },
  { href: "/notice", title: "공지사항", hasBack: true },
  { href: "/terms", title: "서비스 약관", hasBack: true },
  { href: "/withdraw", title: "탈퇴하기", hasBack: true },
  { href: "/pblist/recommend", title: "추천 PB 리스트", hasBack: true },
  { href: "/pblist", title: "PB 찾기", hasBack: true },
  { href: "/schedule/changeTime", title: "상담 가능 시간 변경하기", hasBack: true },
  { href: "/schedule", title: "일정관리", hasBack: true },
];
