import ReactQueryProvider from "./ReactQueryProvider";
import "./globals.css";
import { Noto_Sans } from "next/font/google";

const noto = Noto_Sans({ weight: ["100", "300", "400", "500", "700", "900"], subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={noto.className}>
        <main>{children}</main>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
